[package]
name = "casabaldini"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
dioxus = { version = "0.7", features = ["fullstack"] }
serde = { version = "1.0.228", features = ["derive"] }
