[workspace]
members = [
    "backend",
    "frontend",
    "shared"
]

resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
dioxus = "0.7.2"
dioxus-ssr = "0.7.2"